services:
  app:
    build: 
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - /app/node_modules
      - .:/app:delegated
    ports:
      - "8000:8000"
    command: ["npm", "run", "dev"]